### ISSUE TITLE
document deletion not handled correctly

### ISSUE THREAD

**Issue by azliu0** [techx/pigeon#15]
document deletion is not handled in the most robust manner. in particular, they are not deleted from generated responses that rely on these documents, so when trying to pull up a response to an email that relies on a deleted document, we are issued an error. 

this is easily mitigated by generating a new response, but it would be nice to have documents get deleted from generated responses and/or implement some logic to automatically regenerate responses for existing responses that rely on a deleted document

**Comment by ricchen** [comment]
should be fixed in 01f2e47
